package rough.samples.spring.boot.mybatis.model;

import rough.samples.spring.boot.mybatis.mapper.SplUserMapper;

import java.util.Date;

public class SplUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPL_USER.USER_ID
     *
     * @mbg.generated Tue Jan 21 19:48:16 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPL_USER.USER_CODE
     *
     * @mbg.generated Tue Jan 21 19:48:16 CST 2020
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPL_USER.USER_NAME
     *
     * @mbg.generated Tue Jan 21 19:48:16 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPL_USER.CREATE_TIME
     *
     * @mbg.generated Tue Jan 21 19:48:16 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPL_USER.USER_ID
     *
     * @return the value of SPL_USER.USER_ID
     * @mbg.generated Tue Jan 21 19:48:16 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPL_USER.USER_ID
     *
     * @param userId the value for SPL_USER.USER_ID
     * @mbg.generated Tue Jan 21 19:48:16 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPL_USER.USER_CODE
     *
     * @return the value of SPL_USER.USER_CODE
     * @mbg.generated Tue Jan 21 19:48:16 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPL_USER.USER_CODE
     *
     * @param userCode the value for SPL_USER.USER_CODE
     * @mbg.generated Tue Jan 21 19:48:16 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPL_USER.USER_NAME
     *
     * @return the value of SPL_USER.USER_NAME
     * @mbg.generated Tue Jan 21 19:48:16 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPL_USER.USER_NAME
     *
     * @param userName the value for SPL_USER.USER_NAME
     * @mbg.generated Tue Jan 21 19:48:16 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPL_USER.CREATE_TIME
     *
     * @return the value of SPL_USER.CREATE_TIME
     * @mbg.generated Tue Jan 21 19:48:16 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPL_USER.CREATE_TIME
     *
     * @param createTime the value for SPL_USER.CREATE_TIME
     * @mbg.generated Tue Jan 21 19:48:16 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}