package rough.samples.spring.boot.mybatis.simple.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import rough.samples.spring.boot.mybatis.simple.model.SplUser;

public interface SplUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jan 21 20:37:35 CST 2020
     */
    @Delete({
        "delete from SPL_USER",
        "where USER_ID = RPAD(#{userId,jdbcType=CHAR}, 20, ' ')"
    })
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jan 21 20:37:35 CST 2020
     */
    @Insert({
        "insert into SPL_USER (USER_ID, USER_CODE, ",
        "USER_NAME, CREATE_TIME)",
        "values (#{userId,jdbcType=CHAR}, #{userCode,jdbcType=CHAR}, ",
        "#{userName,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(SplUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jan 21 20:37:35 CST 2020
     */
    @Select({
        "select",
        "USER_ID, USER_CODE, USER_NAME, CREATE_TIME",
        "from SPL_USER",
        "where USER_ID = RPAD(#{userId,jdbcType=CHAR}, 20, ' ')"
    })
    @Results({
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="USER_CODE", property="userCode", jdbcType=JdbcType.CHAR),
        @Result(column="USER_NAME", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    SplUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jan 21 20:37:35 CST 2020
     */
    @Select({
        "select",
        "USER_ID, USER_CODE, USER_NAME, CREATE_TIME",
        "from SPL_USER"
    })
    @Results({
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="USER_CODE", property="userCode", jdbcType=JdbcType.CHAR),
        @Result(column="USER_NAME", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<SplUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jan 21 20:37:35 CST 2020
     */
    @Update({
        "update SPL_USER",
        "set USER_CODE = #{userCode,jdbcType=CHAR},",
          "USER_NAME = #{userName,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}",
        "where USER_ID = RPAD(#{userId,jdbcType=CHAR}, 20, ' ')"
    })
    int updateByPrimaryKey(SplUser record);
}