package rough.samples.spring.boot.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import rough.samples.spring.boot.mybatis.model.SplUser;
import rough.samples.spring.boot.mybatis.model.SplUserExample;

public interface SplUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jun 22 06:10:44 CST 2021
     */
    long countByExample(SplUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jun 22 06:10:44 CST 2021
     */
    int deleteByExample(SplUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jun 22 06:10:44 CST 2021
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jun 22 06:10:44 CST 2021
     */
    int insert(SplUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jun 22 06:10:44 CST 2021
     */
    int insertSelective(SplUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jun 22 06:10:44 CST 2021
     */
    List<SplUser> selectByExample(SplUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jun 22 06:10:44 CST 2021
     */
    SplUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jun 22 06:10:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") SplUser record, @Param("example") SplUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jun 22 06:10:44 CST 2021
     */
    int updateByExample(@Param("record") SplUser record, @Param("example") SplUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jun 22 06:10:44 CST 2021
     */
    int updateByPrimaryKeySelective(SplUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPL_USER
     *
     * @mbg.generated Tue Jun 22 06:10:44 CST 2021
     */
    int updateByPrimaryKey(SplUser record);
}